### PR TITLE
Getting by priority

### PR DESCRIPTION
**Pull request by eustacheAki**
#### What does this PR do?
- This pull request is for getting a task by priority.
#### Description of Task to be completed?
User should get a task by priority and I have below endpoint working
`GET /api/task/priority/{{TaskPriority}}`
#### How should this be manually tested?
- After clone repository (https://github.com/Soma-Technologies-Inc/Backend-To-Do-App/tree/get-by-priority) 
- goes to the root of the project 
- open path into command prompt 
- run the `npm install`
- once setup is done click `npm run startDev` 
- use `git checkout get-by-priority` to navigate to my branch 
- use postman to test
- try to use one of this priority(high, medium, low)
- visit `http://localhost:3000/api/task/priority/high` as an example

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
N/A
#### Screenshot (if appropriate)

### CODE REVIEW

**Comment by tigthor** [comment]
Well Done Eustache.

**Review by tigthor — APPROVED** [review]
Done

**Comment by LouangeMu** [comment]
well done

**Comment by Niyonsengaeric** [comment]
@eustacheAki  try to use the "-" method while you are detailing What does this PR do.
- also provide a way of accessing your branch in your PR description in the section of how should be tested manually use also       
 "-" method.

**Comment by Niyonsengaeric** [comment]
your script "npm run startdev" is not working try to see if you write it correctly!

**Comment by Niyonsengaeric** [comment]
the server is not starting, take a look on the below screenshot and resolve the problem.

eustashe

**Pull request merged**
