### PR TITLE
getAllTasks

### PR DESCRIPTION
**Pull request by Liliane003**
#### What does this PR do?
  

- this task will help the user to get all tasks

- getalltasks to do task

#### Description of Task to be completed?

- this task will help the user to get all tasks

 -  GET /api/task/

#### How should this be manually tested?

- clone this GitHub repo (this can be done either by directly downloading the repo or using your terminal and running git clone https://github.com/Soma-Technologies-Inc/Backend-To-Do-App.git
- open your terminal

- cd into the repo folder which will be created in your local machine

-  run npm install
- git checkout -b ft-getallltasks

- then npm run startdev

- open your Postman or Insomnia (these are the tools used to test apis) then make a request to the endpoint provided

#### Screenshots (if appropriate)
screen

### CODE REVIEW

**Comment by eustacheAki** [comment]
well done

**Comment by tigthor** [comment]
Well Done.

**Review by tigthor — APPROVED** [review]
Approved

**Comment by Niyonsengaeric** [comment]
@Liliane003   please first resolve conflicts!

**Pull request merged**
