### PR TITLE
Feature(gettingtaskbyid)

### PR DESCRIPTION
**Pull request by tigthor**
### What does this PR do?
This PR has the endpoint of getting task by id
### Description of Task to be completed?
I have this api working
`GET /api/task?TaskId=`
### How should this be manually tested?
After cloning the repository [followthislink](https://github.com/Soma-Technologies-Inc/Backend-To-Do-App.git) or Downloading the repo [here](https://github.com/Soma-Technologies-Inc/Backend-To-Do-App/archive/ft-gettingtaskbyid.zip)
- When cloning the repo ou may use `git clone https://github.com/Soma-Technologies-Inc/Backend-To-Do-App.git`
- Navigate to the root of the project open path into your terminal running `cd Backend-To-Do-App` 
- then run `git checkout ft-gettingtaskbyid` in order to navigate to my branch
- run the `npm install`.
- After installation is done run `npm run startDev`  
- Use Postman or Insomnia to test the api by entering the url `http://localhost:3000/api/task?TaskId=` then entering the TaskId you want to find

### Any background context you want to provide?
N/A
### What are the relevant pivotal tracker stories?
N/A

### CODE REVIEW

**Comment by LouangeMu** [comment]
well done

**Comment by EngMutabazi** [comment]
good!!

**Comment by EngMutabazi** [comment]
good!!

**Comment by Niyonsengaeric** [comment]
- In your PR description Guide the way of cloning the repo by adding the command and the link
- also add the way of accessing your branch in how should this be manually tested.
- also provide an example a user can use.

**Comment by Niyonsengaeric** [comment]
check in your returns
 
gettingtaskbyid

**Comment by Niyonsengaeric** [comment]
@tigthor  I am creating a task but I can't find it when I trigger the endpoint.
create task
getbyId

**Comment by tigthor** [comment]
Sorry @Niyonsengaeric  the url to test should be `http://localhost:3000/api/task?TaskId=`

**Comment by Niyonsengaeric** [comment]
@tigthor  can squash your commit into one commit.

**Comment by tigthor** [comment]
Yes I already did that

**Comment by tigthor** [comment]
I worked on the feedback and I successfully squashed my commits into 1

**Pull request merged**
