### PR TITLE
Ft deletebyid

### PR DESCRIPTION
**Pull request by BenieSereine**
#### What does this PR do?
- This helps the user to delete a specific task that he/she does no longer want.

#### Description of Task to be completed?
 We have these endpoints working
 DELETE /api/task/:id

#### How should this be manually tested?
- clone this github repo (this can be done either by directly downloading the repo or using the terminal and run `git clone https://github.com/Soma-Technologies-Inc/Backend-To-Do-App.git`)
- open your terminal
- cd into the repo folder which will be created in the local machine
- then run `npm install`
- then run `npm run startDev`
- open your Postman then make a request to the endpoint provided
#### Example of a user 

http://localhost:3000/api/task
{
 id:1,
name:"Benie"
}
http://localhost:3000/api/task/1

task successfully deleted

#### running the server
Screenshot from 2020-11-14 12-10-48
#### post task
Screenshot from 2020-11-14 12-11-28
#### deleting a specific task
Screenshot from 2020-11-14 12-11-54

### CODE REVIEW

**Comment by Liliane003** [comment]
everything is good

**Comment by tigthor** [comment]
Benie All is working.

**Comment by EngMutabazi** [comment]
welcome  done!!

**Review by tigthor — APPROVED** [review]
All is goo and Working Fine now.

**Comment by Niyonsengaeric** [comment]
@BenieSereine 
-  add the way of accessing your branch in how should this be manually tested.
- also provide an example a user can use.
- provide the screenshots of your postman while you were testing it
- squash your commit into one

**Review by Niyonsengaeric — APPROVED** [review]

**Pull request merged**
